//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediathekClient.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediathekClient.Common.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten: {0}.
        /// </summary>
        internal static string CtrlGbAdminData {
            get {
                return ResourceManager.GetString("CtrlGbAdminData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet als: {0}.
        /// </summary>
        internal static string CtrlLblLogonInfo {
            get {
                return ResourceManager.GetString("CtrlLblLogonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string CtrlMbCaptionError {
            get {
                return ResourceManager.GetString("CtrlMbCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string CtrlMbCaptionInfo {
            get {
                return ResourceManager.GetString("CtrlMbCaptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        internal static string CtrlMbCaptionQuestion {
            get {
                return ResourceManager.GetString("CtrlMbCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string CtrlMbCaptionWarning {
            get {
                return ResourceManager.GetString("CtrlMbCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto kann nicht gelöscht werden. Es muss mindestens ein aktives Konto bestehen bleiben..
        /// </summary>
        internal static string MsgAdminDeletionDelAbortLastAccount {
            get {
                return ResourceManager.GetString("MsgAdminDeletionDelAbortLastAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das eigene Konto kann nicht gelöscht werden..
        /// </summary>
        internal static string MsgAdminDeletionDelAbortOwnAccount {
            get {
                return ResourceManager.GetString("MsgAdminDeletionDelAbortOwnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Argument &quot;{0}&quot; mit Wert &quot;{1}&quot;..
        /// </summary>
        internal static string MsgCommonArgumentException {
            get {
                return ResourceManager.GetString("MsgCommonArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie wirklich Löschen?
        ///Die Änderungen können nicht mehr Rückgängig gemacht werden..
        /// </summary>
        internal static string MsgCommonCommonDeleteConfirmation {
            get {
                return ResourceManager.GetString("MsgCommonCommonDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschung fehlgeschlagen..
        /// </summary>
        internal static string MsgCommonErrorDeletionFailed {
            get {
                return ResourceManager.GetString("MsgCommonErrorDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist eine Ausnahme aufgetreten:
        ///{0}.
        /// </summary>
        internal static string MsgCommonErrorExceptionOccured {
            get {
                return ResourceManager.GetString("MsgCommonErrorExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Format.
        /// </summary>
        internal static string MsgCommonErrorInvalidFormat {
            get {
                return ResourceManager.GetString("MsgCommonErrorInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wird ein Wert benötigt..
        /// </summary>
        internal static string MsgCommonErrorMissingData {
            get {
                return ResourceManager.GetString("MsgCommonErrorMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Daten gefunden..
        /// </summary>
        internal static string MsgCommonErrorNoDataFound {
            get {
                return ResourceManager.GetString("MsgCommonErrorNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde nichts selektiert..
        /// </summary>
        internal static string MsgCommonErrorNothingSelected {
            get {
                return ResourceManager.GetString("MsgCommonErrorNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern fehlgeschlagen..
        /// </summary>
        internal static string MsgCommonErrorSaveFailed {
            get {
                return ResourceManager.GetString("MsgCommonErrorSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Erstellung war erfolgreich..
        /// </summary>
        internal static string MsgCommonInfoCreationSuccess {
            get {
                return ResourceManager.GetString("MsgCommonInfoCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschung erfolgreich..
        /// </summary>
        internal static string MsgCommonInfoDeletionSuccess {
            get {
                return ResourceManager.GetString("MsgCommonInfoDeletionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Daten wurden gespeichert..
        /// </summary>
        internal static string MsgCommonInfoSaveSuccess {
            get {
                return ResourceManager.GetString("MsgCommonInfoSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden nicht alle Felder ausgefüllt..
        /// </summary>
        internal static string MsgCommonMissingValues {
            get {
                return ResourceManager.GetString("MsgCommonMissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Medien ausgewählt..
        /// </summary>
        internal static string MsgCommonNoMediaSelected {
            get {
                return ResourceManager.GetString("MsgCommonNoMediaSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Kunde ausgewählt..
        /// </summary>
        internal static string MsgCommonNoUserSelected {
            get {
                return ResourceManager.GetString("MsgCommonNoUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Auswahl wird nicht unterstützt..
        /// </summary>
        internal static string MsgCommonSelectionNotHandled {
            get {
                return ResourceManager.GetString("MsgCommonSelectionNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anmeldedaten sind ungültig.
        /// </summary>
        internal static string MsgLogonInvalid {
            get {
                return ResourceManager.GetString("MsgLogonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Bild kann nur für bereits gespeicherte Medien angezeigt/geändert werden..
        /// </summary>
        internal static string MsgMediaImageNotShowable {
            get {
                return ResourceManager.GetString("MsgMediaImageNotShowable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Ausleih-Aufträge erstellt..
        /// </summary>
        internal static string MsgMediaLendingsCreateFailure {
            get {
                return ResourceManager.GetString("MsgMediaLendingsCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Ausleihungen wurden erfolgreich im System gespeichert..
        /// </summary>
        internal static string MsgMediaLendingsCreateSuccess {
            get {
                return ResourceManager.GetString("MsgMediaLendingsCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für einige Medien gab es bestehende Reservationen (mit älterem Reservations-Datum).
        ///
        ///Dies betrifft die folgenden Medien:
        ///{0}
        ///
        ///Die Medien können nicht ausgeliehen werden! Sie können jedoch reserviert werden..
        /// </summary>
        internal static string MsgMediaRentAlreadyLongerReservations {
            get {
                return ResourceManager.GetString("MsgMediaRentAlreadyLongerReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Reservationen wurden erstellt..
        /// </summary>
        internal static string MsgMediaReservationsCreateSuccess {
            get {
                return ResourceManager.GetString("MsgMediaReservationsCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Medien wurden erfolgreich retourniert..
        /// </summary>
        internal static string MsgMediaReturnSuccess {
            get {
                return ResourceManager.GetString("MsgMediaReturnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer hat im Moment keine Medien ausgeliehen..
        /// </summary>
        internal static string MsgMediaUserHasNoOpenLendings {
            get {
                return ResourceManager.GetString("MsgMediaUserHasNoOpenLendings", resourceCulture);
            }
        }
    }
}
